# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Sum R
tagline:             'A Jekyll theme'
description:         ''
url:                 http://sumaiyar.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sumaiya Rahman
  url:               https://twitter.com/RSumaiya
  email:             sumaiyar@protonmail.com

# Custom vars
version:             1.0.0
